import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ExternalLink } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { portfolioProjects } from '../data/portfolioProjects';
import './PortfolioPage.css';

const categories = ['All', ...new Set(portfolioProjects.map((project) => project.industry))];
export default function PremiumPortfolioPage() {
  const [activeCategory, setActiveCategory] = useState('All');
  useEffect(() => { window.scrollTo(0, 0); }, []);
  const projects = activeCategory === 'All' ? portfolioProjects : portfolioProjects.filter((project) => project.industry === activeCategory);
  return <main className="portfolio-page"><Helmet><title>Our Work & Portfolio | SignalLight Studio</title><meta name="description" content="Explore conversion-focused websites and in-depth digital case studies created by SignalLight Studio for ambitious service businesses." /><link rel="canonical" href="https://www.signallightstudio.com/portfolio" /></Helmet><section className="portfolio-hero section-dark text-center"><div className="container reveal"><div className="badge" style={{ marginBottom: '1rem' }}>Selected work</div><h1>Websites built to move businesses forward.</h1><p className="subtitle" style={{ maxWidth: '700px', margin: '0 auto' }}>Explore the strategy, craft, and measurable thinking behind every project.</p></div></section><section className="portfolio-gallery section section-light"><div className="container"><div className="portfolio-filters reveal">{categories.map((category) => <button type="button" key={category} className={`filter-btn ${activeCategory === category ? 'active' : ''}`} onClick={() => setActiveCategory(category)} aria-pressed={activeCategory === category}>{category}</button>)}</div><div className="portfolio-page-grid">{projects.map((project) => <article key={project.id} className="portfolio-detail-card"><div className="portfolio-image-container"><img src={project.heroImage} alt={`${project.title} website`} width="760" height="600" loading="lazy" decoding="async" /><div className="portfolio-category-badge">{project.industry}</div></div><div className="portfolio-detail-content"><span className="portfolio-location">{project.location}</span><h2><Link className="portfolio-card-link" to={`/portfolio/${project.slug}`}>{project.title}</Link></h2><p className="portfolio-desc">{project.overview}</p><div className="portfolio-meta-grid"><div><span className="meta-title">Services</span><ul className="meta-list">{project.services.map((item) => <li key={item}>{item}</li>)}</ul></div><div><span className="meta-title">Technology</span><ul className="meta-list">{project.technologies.map((item) => <li key={item}>{item}</li>)}</ul></div></div><div className="portfolio-card-actions"><Link to={`/portfolio/${project.slug}`} className="btn btn-primary">View Case Study <ArrowRight size={18} /></Link><a href={project.liveDemo} target="_blank" rel="noreferrer" className="btn btn-outline">Live Site <ExternalLink size={16} /></a></div></div></article>)}</div></div></section></main>;
}
